name: 'moex_fund_compare'
version: '1.0.0'

profile: 'dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  moex_fund_compare:
    staging:
      +materialized: view