name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -q pytest requests psycopg2-binary

      - name: Run smoke tests
        run: pytest ingestion/tests/test_smoke.py -v
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Lint Python code
        run: |
          pip install -q ruff
          ruff check .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
          terraform_wrapper: false

      - name: Write Yandex Cloud key
        run: |
          mkdir -p infra/terraform
          echo '${{ secrets.YC_KEY_JSON }}' > infra/terraform/key.json

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo '${{ secrets.SSH_PUBLIC_KEY }}' > ~/.ssh/id_rsa.pub

      - name: Terraform Init & Validate
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_ssh_public_key_path: ~/.ssh/id_rsa.pub
        run: |
          terraform init
          terraform validate

      - name: Build Docker images
        run: |
          docker compose build --no-cache api
          docker compose build --no-cache airflow-webserver

      - name: Terraform Apply
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_ssh_public_key_path: ~/.ssh/id_rsa.pub
          TF_VAR_postgres_password: ${{ secrets.TF_VAR_postgres_password }}
        run: terraform apply -auto-approve

      - name: Get VM IP
        id: vm_ip
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "ip=$(terraform output -raw vm_external_ip)" >> $GITHUB_OUTPUT

      - name: Redeploy application on VM
        env:
          VM_IP: ${{ steps.vm_ip.outputs.ip }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$VM_IP "
            sudo chown -R ubuntu:ubuntu /opt/moex-etf &&
            cd /opt/moex-etf &&
            git fetch origin &&
            git reset --hard origin/main &&
            docker compose up --build -d
          "